//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Front.Api.CustomerScreen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerScreenLocalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerScreenLocalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resto.Front.Api.CustomerScreen.Resources.CustomerScreenLocalResources", typeof(CustomerScreenLocalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кол-во.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В системе остутствует второй монитор..
        /// </summary>
        public static string CantFindSecondScreenError {
            get {
                return ResourceManager.GetString("CantFindSecondScreenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сдача: .
        /// </summary>
        public static string ChangeSumText {
            get {
                return ResourceManager.GetString("ChangeSumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции.
        /// </summary>
        public static string ConfigOperations {
            get {
                return ResourceManager.GetString("ConfigOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пере­запус­тить видео.
        /// </summary>
        public static string ConfigRestartPlayer {
            get {
                return ResourceManager.GetString("ConfigRestartPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстано­вить окно.
        /// </summary>
        public static string ConfigValidareWindow {
            get {
                return ResourceManager.GetString("ConfigValidareWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экран покупателя был повторно проинициализирован, проверьте результат..
        /// </summary>
        public static string CusromerScreenShowSuccess {
            get {
                return ResourceManager.GetString("CusromerScreenShowSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка: .
        /// </summary>
        public static string DiscountText {
            get {
                return ResourceManager.GetString("DiscountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По указанному пути не найдено ни одного подходящего для воспроизведения видеофайла. Удостоверьтесь, что файлы есть и перезапустите iikoFront..
        /// </summary>
        public static string FilesNotFoundErrorText {
            get {
                return ResourceManager.GetString("FilesNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надбавка: .
        /// </summary>
        public static string IncreaseText {
            get {
                return ResourceManager.GetString("IncreaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string InfoMessageTitle {
            get {
                return ResourceManager.GetString("InfoMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержание заказа:.
        /// </summary>
        public static string OrderContent {
            get {
                return ResourceManager.GetString("OrderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма заказа:.
        /// </summary>
        public static string OrderSum {
            get {
                return ResourceManager.GetString("OrderSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экран покупателя.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to стоимость.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого: .
        /// </summary>
        public static string TotalSumText {
            get {
                return ResourceManager.GetString("TotalSumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать!.
        /// </summary>
        public static string WelcomeTextDefault {
            get {
                return ResourceManager.GetString("WelcomeTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окно покупателя.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
